namespace Book_store_1_.DTOs
{
    public class Bookdto()
    {
        // add properities that we need to take from request
        // NEVER TAKE PRIMARY KEY FROM REQUEST
        //      --> IT is autogenerated 
        
       
        public string? Book_Name{set; get;}

        public DateTime Release_date{set; get;}

        public byte Category_Id{set; get;}

        public string? Author{set; get;}

        public int Number_Of_Copies{set; get;}
    }
}