namespace Book_store_1_.DTOs
{
    public class Bookdto()
    {
        // add properities that we need to take from request
        // NEVER TAKE PRIMARY KEY FROM REQUEST
        //      --> IT is autogenerated 
        // public int BookId {set;}
       
        public string? BookName{set; get;}

        public DateTime ReleaseDate{set; get;}

        public byte CategoryId{set; get;}

        public string? Author{set; get;}

        public int NumberOfCopies{set; get;}
    }
}