// <auto-generated />
using System;
using Book_store_1_.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_store_1_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_store_1_.Models.Admin", b =>
                {
                    b.Property<int>("Admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_Id");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Book_store_1_.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Book_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Category_Id")
                        .HasColumnType("tinyint");

                    b.Property<int>("Number_Of_Copies")
                        .HasColumnType("int");

                    b.Property<DateTime>("Release_date")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId");

                    b.HasIndex("Category_Id");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("Book_store_1_.Models.Borrowed_books", b =>
                {
                    b.Property<int>("BorrowedBooksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowedBooksId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Borrow_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Return_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("BorrowedBooksId");

                    b.HasIndex("BookId");

                    b.HasIndex("User_Id");

                    b.ToTable("Borrowed_Books", (string)null);
                });

            modelBuilder.Entity("Book_store_1_.Models.Category", b =>
                {
                    b.Property<byte>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Category_Id"));

                    b.Property<string>("Category_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Category_Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Book_store_1_.Models.Member", b =>
                {
                    b.Property<int>("Member_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Member_Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_borrowedBooks")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Member_Id");

                    b.HasIndex("BookId");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Book_store_1_.Models.Book", b =>
                {
                    b.HasOne("Book_store_1_.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Book_store_1_.Models.Borrowed_books", b =>
                {
                    b.HasOne("Book_store_1_.Models.Book", "Book")
                        .WithMany("Borrowed_Books")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book_store_1_.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Book_store_1_.Models.Member", b =>
                {
                    b.HasOne("Book_store_1_.Models.Book", null)
                        .WithMany("Members")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("Book_store_1_.Models.Book", b =>
                {
                    b.Navigation("Borrowed_Books");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Book_store_1_.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
